apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hospital-prod

resources:
  - namespace.yaml
  - ../../base

replicas:
  - name: fe-deployment-v1
    count: 3
  - name: be-deployment-v1
    count: 3

images:
  - name: 606030503959.dkr.ecr.us-east-1.amazonaws.com/ecr-fe
    newName: 606030503959.dkr.ecr.us-east-1.amazonaws.com/ecr-fe
    newTag: 043045c9c50adeab96cb419d9f15ee52005195e7
  - name: 606030503959.dkr.ecr.us-east-1.amazonaws.com/ecr-be
    newName: 606030503959.dkr.ecr.us-east-1.amazonaws.com/ecr-be
    newTag: 043045c9c50adeab96cb419d9f15ee52005195e7
