apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hospital-prod

resources:
  - namespace.yaml
  - ../../base

replicas:
  - name: fe-deployment-v1
    count: 3
  - name: be-deployment-v1
    count: 3

images:
  - name: 606030503959.dkr.ecr.us-east-1.amazonaws.com/ecr-fe
    newName: 606030503959.dkr.ecr.us-east-1.amazonaws.com/ecr-fe
    newTag: 5749d0c96c6d660bffaaa322665878fb3fb2f64a
  - name: 606030503959.dkr.ecr.us-east-1.amazonaws.com/ecr-be
    newName: 606030503959.dkr.ecr.us-east-1.amazonaws.com/ecr-be
    newTag: 5749d0c96c6d660bffaaa322665878fb3fb2f64a
