apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hospital-prod

resources:
  - namespace.yaml
  - ../../base

replicas:
  - name: fe-deployment-v1
    count: 3
  - name: be-deployment-v1
    count: 6

images:
  - name: 606030503959.dkr.ecr.us-east-1.amazonaws.com/ecr-fe
    newName: 606030503959.dkr.ecr.us-east-1.amazonaws.com/ecr-fe
    newTag: 69d170e0108a53e6b1a1905dfdf5bdfeb4657c7e
  - name: 606030503959.dkr.ecr.us-east-1.amazonaws.com/ecr-be
    newName: 606030503959.dkr.ecr.us-east-1.amazonaws.com/ecr-be
    newTag: 69d170e0108a53e6b1a1905dfdf5bdfeb4657c7e
