apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: hospital
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
      app.kubernetes.io/component: metrics
  namespaceSelector:
    matchNames:
      - hospital-prod
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s

