apiVersion: v1
kind: Secret
metadata:
  name: be-redis-secret
  namespace: hospital-prod
type: Opaque
stringData:
  connection-string: redis-sentinel.hospital-prod.svc.cluster.local:26379,serviceName=mymaster,password=<REDIS_PASSWORD>,abortConnect=false
