apiVersion: v1
kind: Secret
metadata:
  name: be-redis-secret
  namespace: hospital-prod
type: Opaque
stringData:
  connection-string: redis-primary.hospital-prod.svc.cluster.local:6379,password=<REDIS_PASSWORD>,abortConnect=false

