apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hospital-prod

resources:
  - 10-redis-configmap.yaml
  - 20-redis-services.yaml
  - 30-redis-statefulset.yaml
  - 40-redis-servicemonitor.yaml
  - 50-redis-networkpolicy.yaml

