apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - policies/disallow-privileged-containers.yaml
  - policies/require-run-as-non-root.yaml
  - policies/require-resource-limits.yaml
  - eso/cluster-secret-store.yaml


