apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://falcosecurity.github.io/charts
    chart: falco
    targetRevision: "8.0.3"
    helm:
      releaseName: falco
      values: |
        driver:
          kind: modern_ebpf

        falco:
          jsonOutput: true

        serviceMonitor:
          create: true

        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1Gi

  destination:
    server: https://kubernetes.default.svc
    namespace: security

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
