apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: be-db-secret
  namespace: hospital
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: be-db-secret
    creationPolicy: Owner
  data:
    - secretKey: default-connection
      remoteRef:
        key: hospital-db-connection
        property: default-connection
