apiVersion: generators.external-secrets.io/v1alpha1
kind: ECRAuthorizationToken
metadata:
  name: ecr-token-gen
  namespace: hospital
spec:
  region: us-east-1
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ecr-registry-secret
  namespace: hospital
spec:
  refreshInterval: 1h
  target:
    name: ecr-registry-secret
    template:
      type: kubernetes.io/dockerconfigjson
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: ECRAuthorizationToken
        name: ecr-token-gen
