apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 05-fe-deployment.yaml
  - 06-fe-service.yaml
  - 07-be-deployment.yaml
  - 08-be-service.yaml
  - 10-network-policy.yaml
  - 11-fe-hpa.yaml
  - 12-be-hpa.yaml
